excluded_categories:
  type: list
  default: ""
  description:
    en: "List of excluded category slugs"
order_by_activity:
  type: list
  default: ""
  description:
    en: "Categories where children are ordered by activity"
show_latest:
  type: list
  default: ""
  description:
    en: "Categories to show latest (unread + new) topic counts for"
collapsible_sidebar:
  type: bool
  default: false
  description:
    en: "Adds the ability to collapse the sidebar to show only category logos. This setting will also create a category logo when one is not present."
custom_links:
  type: list
  default: ""
  description:
    en: |
      Add custom links to the category sidebar.</br>
      Format (comma seperated): name, icon url, link url, options</br>
      Options (colon seperated):
        location: 'above' or 'below', default: 'above';</br>
        new_tab: 'true' or 'false', default: 'false';